//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities2 : DbContext
    {
        public testEntities2()
            : base("name=testEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aftersalerequest> aftersalerequests { get; set; }
        public DbSet<cschat> cschats { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<feedback> feedbacks { get; set; }
        public DbSet<inventory> inventories { get; set; }
        public DbSet<invoice> invoices { get; set; }
        public DbSet<logistic> logistics { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productionplan> productionplans { get; set; }
        public DbSet<quotation> quotations { get; set; }
        public DbSet<returnrequest> returnrequests { get; set; }
        public DbSet<shipment> shipments { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<workorder> workorders { get; set; }
    }
}
