//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Collections.Generic;
    
    public partial class cschat
    {
        public int ChatID { get; set; }
        public int CustomerID { get; set; }
        public string Message { get; set; }
        public string Response { get; set; }
        public string Timestamp { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
