//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.cschats = new HashSet<cschat>();
            this.feedbacks = new HashSet<feedback>();
            this.orders = new HashSet<order>();
            this.quotations = new HashSet<quotation>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Feedback { get; set; }
        public int Phone { get; set; }
    
        public virtual ICollection<cschat> cschats { get; set; }
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<quotation> quotations { get; set; }
    }
}
