//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.aftersalerequests = new HashSet<aftersalerequest>();
            this.invoices = new HashSet<invoice>();
            this.returnrequests = new HashSet<returnrequest>();
            this.shipments = new HashSet<shipment>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        public virtual ICollection<aftersalerequest> aftersalerequests { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual ICollection<returnrequest> returnrequests { get; set; }
        public virtual ICollection<shipment> shipments { get; set; }
    }
}
