//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int PaymentID { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Amount { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
