//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.inventories = new HashSet<inventory>();
            this.quotations = new HashSet<quotation>();
            this.returnrequests = new HashSet<returnrequest>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public int StockQuantity { get; set; }
    
        public virtual ICollection<inventory> inventories { get; set; }
        public virtual ICollection<quotation> quotations { get; set; }
        public virtual ICollection<returnrequest> returnrequests { get; set; }
    }
}
