//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSunshineToy
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        public shipment()
        {
            this.logistics = new HashSet<logistic>();
        }
    
        public int shipmentID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> TrackingNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
    
        public virtual ICollection<logistic> logistics { get; set; }
        public virtual order order { get; set; }
    }
}
